name: v_vpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.3.0

  # Encourages good practices
  flutter_lints: ^5.0.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/